### ISSUE TITLE
[bug] Training stopped at 1000 epoch

### ISSUE THREAD

**Issue by TomohikoNakamura** [ben-hayes/neural-waveshaping-synthesis#6]
Very interesting work!
I'm trying to train the model with the URMP dataset for reproducing the results, and I encountered the training stopped at 1000 epoch. I think this is a bug. I found that the default value of `max_epochs`  of `pytorch_lightning.Trainer` of 1.1.2 version (specified in the requirement txt file) is 1000, which causes the problem (see https://github.com/PyTorchLightning/pytorch-lightning/blob/1.1.2/pytorch_lightning/trainer/trainer.py#L103). Should I use a different version of pytorch-lightning ? or should I set `max_epochs=None` ?

**Comment by ben-hayes** [comment]
Hi @TomohikoNakamura 

That is odd — are you using the [train_newt.gin](https://github.com/ben-hayes/neural-waveshaping-synthesis/blob/cb7aaea0412c9dc0f46004e2f1656217f065d333/gin/train/train_newt.gin) file provided to configure the `pl.Trainer`? As far as I'm aware, the `max_steps` parameter, which is specified in the .gin file, _should_ override the `max_epochs` default.

If you are, then bumping the pytorch-lightning version or setting `max_epochs=None` would both be valid workarounds for now. You could also just set `max_epochs` in the .gin file so that it's greater than max_steps / num_batches. In any case, I'll look into it and try to push a fix in the next couple of days.

Cheers
Ben

**Comment by TomohikoNakamura** [comment]
Hi Ben,

Thank you for your reply and addressing this issue.
I prepared the URMP data and ran the training script, following [README.md](https://github.com/ben-hayes/neural-waveshaping-synthesis/blob/main/README.md#training). So, I used `train_new.gin` provided by this repository.
After sending this issue, I examined this problem in details, and I think this may be a bug of pytorch-lightening 1.1.2.

To check the value of `max_epochs`, I inserted the following two lines after [the 76th line in `scripts/train.py`](https://github.com/ben-hayes/neural-waveshaping-synthesis/blob/main/scripts/train.py#L76).
```
    print("trainer_kwargs:", kwargs)
    print("max_epochs:", trainer.max_epochs)
    return
```
And, I got the following output.
```bash
root@609a4156a100:/data/ssd/workspace/nes# python scripts/train.py --gin-file gin/train/train_newt.gin --dataset-path data/urmp --urmp --instrument vn --load-data-to-memory
GPU available: True, used: True
TPU available: None, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
trainer_kwargs: {'max_steps': 120000, 'gradient_clip_val': 2.0, 'accelerator': 'dp'}
max_epochs: 1000
```
Updating pytorch-lightening to its latest version solved this problem (I confirmed `max_epochs` was set as `None`).

I checked the above results in a docker container created by the following Dockerfile.
```Dockerfile
FROM nvcr.io/nvidia/pytorch:21.06-py3

ENV DEBIAN_FRONTEND=noninteractive

# Set default shell to /bin/bash
SHELL ["/bin/bash", "-cu"]

RUN apt-get update && apt-get install -y --allow-downgrades --allow-change-held-packages --no-install-recommends \
        build-essential \
    	ffmpeg \
        git \
        vim \
        wget \
		curl \
		ca-certificates \
		less \
		lv

# Install pytorch
RUN pip install auraloss==0.2.1 black==20.8b1 click==7.1.2 gin-config==0.4.0 librosa==0.8.0 numpy==1.20.1 pytorch_lightning==1.1.2 resampy==0.2.2 scipy==1.6.1 torchcrepe==0.0.12 wandb
```

Best regards,
@TomohikoNakamura
